### ISSUE TITLE
Exibição do nome do curso na lista de cursos

### ISSUE THREAD

**Issue by flaviorscorreia** [brunowelber/training-4-all#1]
Na composição dos itens da lista que exibe os cursos cadastrados no banco, não estamos conseguindo exibir o nome do curso propriamente dito. Conseguimos exibir a "descrição curta", a "descrição longa" e qualquer outro detalhe, exceto o nome do curso.
Confirmamos que o nome do curso está sendo cadastrado corretamente no banco de dados.
Não conseguimos encontrar nenhum indicio de problema no arquivo "cursoController" e nem no "editar.blad.php".
Vale lembrar que não é exibida nenhuma mensagem de erro, o dado simplesmente não é exibido.

**Comment by brunowelber** [comment]
Ajustado. Alguém havia criado a coluna com a primeira letra em maiúscula, por tanto ao se recuperar o dado ele esperava chamar por "Nome" com N maiúsculo. Usem o comando 
php artisan migrate:refresh
para refazer todo o banco, aproveitei e fiz os relacionamentos da autor_curso.
